# Generated by Django 5.2.7 on 2026-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staff_schedule_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffworkinghours',
            name='unique_staff_day',
        ),
        migrations.AlterField(
            model_name='staffbreaktime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffworkinghours',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='staffworkinghours',
            unique_together={('staff', 'day')},
        ),
    ]
