# Generated by Django 5.2.7 on 2026-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('consultation', 'Consultation'), ('converted', 'Converted'), ('lost', 'Lost'), ('returning', 'Returning'), ('vip', 'VIP')], default='new', max_length=20),
        ),
    ]
