name: aura-clinic-backend
region: nyc

services:
  - name: web
    github:
      repo: harideepak-10/auro_clinic
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: gunicorn aura_backend.wsgi:application --bind 0.0.0.0:8080
    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        value: "*"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: DISABLE_COLLECTSTATIC
        scope: RUN_TIME
        value: "1"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs