# Generated by Django 5.2.7 on 2026-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('pre_care', models.TextField(blank=True)),
                ('post_care', models.TextField(blank=True)),
                ('frequency', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
