import '../model/patient_model.dart';

class StaticPatientData {
  static List<PatientModel> patients = [
    PatientModel(
      id: 'AURA-001',
      name: 'Isabelle Morel',
      email: 'isabelle@example.com',
      phone: '+33 6 12 34 56 78',
      city: 'Paris',
      country: 'France',
      gender: 'Female',
      dob: '1992-05-15',
      bloodType: 'O+',
      allergies: 'None',
      skinType: 'Combination',
      contraindications: 'None',
      marketingSource: 'Instagram',
      image: 'https://i.pinimg.com/736x/7d/f2/fb/7df2fbc4f4d2e2f9e48e70fa7a9999c4.jpg',
      category: 'Returning',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    PatientModel(
      id: 'AURA-002',
      name: 'Julian Schmidt',
      email: 'julian@example.com',
      phone: '+49 151 2345678',
      city: 'Berlin',
      country: 'Germany',
      gender: 'Male',
      dob: '1988-11-20',
      bloodType: 'A-',
      allergies: 'Peanuts',
      skinType: 'Oily',
      contraindications: 'Sensitive Skin',
      marketingSource: 'Google Search',
      image: 'https://i.pinimg.com/736x/f2/63/37/f26337907cce687a3fbfed7f13651975.jpg',
      category: 'New',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    PatientModel(
      id: 'AURA-003',
      name: 'Sophie Dubois',
      phone: '+33 6 98 76 54 32',
      city: 'Lyon',
      country: 'France',
      gender: 'Female',
      dob: '1995-02-10',
      skinType: 'Dry',
      marketingSource: 'Facebook',
      image: 'https://i.pinimg.com/736x/7d/f2/fb/7df2fbc4f4d2e2f9e48e70fa7a9999c4.jpg',
      category: 'Lead',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    PatientModel(
      id: 'AURA-004',
      name: 'Emma Watson',
      email: 'emma@example.com',
      phone: '+44 7700 900000',
      city: 'London',
      country: 'UK',
      gender: 'Female',
      image: 'https://i.pinimg.com/736x/f2/63/37/f26337907cce687a3fbfed7f13651975.jpg',
      category: 'VIP',
      createdAt: DateTime.now().subtract(const Duration(days: 365)),
    ),
  ];
}
