# Generated by Django 5.2.7 on 2026-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Returning', 'Returning'), ('VIP', 'VIP'), ('Lead', 'Lead')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marketing_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='skin_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
