# Generated by Django 5.2.7 on 2026-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_blood_type_patient_category_patient_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marketing_source',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Website', 'Website'), ('Walk-in', 'Walk-in'), ('Referral', 'Referral'), ('WhatsApp', 'WhatsApp'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Dry', 'Dry'), ('Oily', 'Oily'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive')], max_length=50),
        ),
    ]
