# Generated by Django 5.2.7 on 2026-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_blood_type_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='marketing_source',
            field=models.IntegerField(blank=True, choices=[(1, 'Instagram'), (2, 'Website'), (3, 'Walk-in'), (4, 'Referral'), (5, 'WhatsApp'), (6, 'Other')], null=True),
        ),
    ]
